spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
    
    
logging:
  level:
    ROOT: INFO
    org.spring.security: INFO
    org.hibernate: INFO
    org.springframework.web: INFO